version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - database.env

  db_migrations:
    image: tl-migrate
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      - POSTGRES_DB_HOST=db
    command: version

  tl_server:
    image: tl-server
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      - POSTGRES_DB_HOST=db
      - PORT=80
