version: '3'

services:
  db:
    image: postgres:12
    env_file:
      - database.env

  db_migrations:
    image: tl-migrate
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      - POSTGRES_DB_HOST=db
    command: version

  tl_server:
    image: tl-server
    restart: always
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      - POSTGRES_DB_HOST=db
      - PORT=80

  tl_front:
    image: tl-front
    restart: always

  tl_proxy:
    image: tl-proxy
    restart: always
    depends_on:
      - tl_front
      - tl_server
